### ISSUE TITLE
Scrolling not working on mobile devices

### ISSUE THREAD

**Issue by photon43** [Mango/slideout#132] opened 2015-11-02 21:44 UTC
Got everything working great except that when the menu in the slide out is vertically longer that the viewport (very common in landscape orientation), the user can not scroll the menu vertically to reveal the rest of the menu items.  This does work on desktop clients with the default ugly sidebars but seems to be entirely non functional on mobile touch devices.

Even testing the demo at https://mango.github.io/slideout/ yields the same behavior. 
Am I missing something? It is otherwise a really great solution for us here. Please advise. Thank you!

**Comment by photon43** [comment] 2015-11-02 22:17
I have already @Vinsanity suggested CSS improvements found here: https://github.com/Mango/slideout/pull/102. Still not working though. Thoughts?

**Comment by quuack** [comment] 2015-11-03 11:12
I think the issue resides in the following function, which seems to prevent the panel from scrolling when the menu is opened.

/**
   * Prevents touchmove event if slideout is moving
   */
  this._preventMove = function(eve) {
    if (self._moved || self._opened) {
      //eve.preventDefault();
    }
  };

Commenting fixes it partially (allows panell scrolling while the menu is active which is not cool)  but the right fix would be preventing default ONLY when the evt target is a panel's child element and not any element.

**Comment by janwidmer** [comment] 2015-11-03 15:59
I have the same problem, seems to be introduced by the newest release. I have it successfully working with version 0.1.9

**Comment by pazguille** [comment] 2015-11-03 16:52
Sorry guys! Thanks for reporting this. Fixed on v0.1.11.

**Closed by pazguille** 2015-11-03 16:52 UTC
Labels: bug

**Comment by photon43** [comment] 2015-11-03 20:11
Great! Thank you!

**Comment by janwidmer** [comment] 2015-11-04 09:05
Perfect. Works again, thanks for the quick fix.

**Comment by vitobotta** [comment] 2016-03-31 14:09
Hi! I am using the latest version but I still have this issue. All works fine apart from the fact that when I have the phone in landscape mode the menu is not scrollable and some items are not visible. Do I need to do something else other than use the latest version?

Thanks in advance :)

**Comment by vitobotta** [comment] 2016-04-01 11:34
Looks like the problem for me was caused by this code

`document.addEventListener('touchmove', preventDefault, false)`

which I had for the "pull to refresh" action done with iScroll. I have resolved by removing this listener when the side menu is open so to allow for native scrolling of the menu:

 ```
 App.slideout.on 'beforeopen', ->
    document.removeEventListener('touchmove', preventDefault, false)

  App.slideout.on 'beforeclose', ->
    document.addEventListener('touchmove', preventDefault, false)
```

Seems to work fine now...
